##############################
# Netlify configuration file #
##############################


# List of Build plugins
# Use the current plugin in builds for testing and debugging.
# Local path to the plugin.
package = "."
[[plugins]]
    package = "netlify-plugin-astra"
    [plugins.inputs]


[build]
# Dummy build command
command = "echo onBuild"

[build.environment]
NODE_VERSION = "12.18.0"
